name: gridworld
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - astroid=2.3.3=py37_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2020.6.24=0
  - certifi=2020.6.20=py37_0
  - cffi=1.13.2=py37h2e261b9_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - entrypoints=0.3=py37_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.4=243
  - ipykernel=5.3.0=py37h5ca1d4c_0
  - ipython=7.16.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - isort=4.3.21=py37_0
  - jedi=0.17.1=py37_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=6.1.5=py_0
  - jupyter_core=4.6.3=py37_0
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.1=h8b12597_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mccabe=0.6.1=py37_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - parso=0.7.0=py_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=6.2.1=py37h34e0f95_0
  - pip=19.3.1=py37_0
  - prompt-toolkit=3.0.5=py_0
  - protobuf=3.11.1=py37he1b5a44_0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.6.1=py_0
  - pylint=2.4.4=py37_0
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.1=py_0
  - pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pyzmq=19.0.1=py37he6710b0_1
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.22.1=py37hd81dba3_0
  - setuptools=42.0.1=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tabulate=0.8.3=py37_0
  - tensorboardx=1.9=py_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.4.2=py37_cu101
  - tornado=6.0.4=py37h7b6447c_1
  - traitlets=4.3.3=py37_0
  - wheel=0.33.6=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.2=he6710b0_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - astunparse==1.6.3
    - attrs==19.3.0
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.0
    - cloudpickle==1.2.2
    - colorama==0.4.3
    - cycler==0.10.0
    - data==0.4
    - decorator==4.4.1
    - filelock==3.0.12
    - funcsigs==1.0.2
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.18.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.30.0
    - gym==0.15.4
    - h5py==2.10.0
    - idna==2.8
    - imageio==2.6.1
    - imageio-ffmpeg==0.3.0
    - importlib-metadata==1.3.0
    - jsonschema==3.2.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - latex==0.7.0
    - markdown==3.2.2
    - matplotlib==3.2.2
    - more-itertools==8.0.2
    - moviepy==1.0.1
    - oauthlib==3.1.0
    - opencv-python==4.1.2.30
    - opt-einsum==3.2.1
    - packaging==19.2
    - pluggy==0.13.1
    - proglog==0.1.9
    - psutil==5.6.7
    - py==1.8.0
    - py-spy==0.3.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.3.2
    - pyparsing==2.4.5
    - pyqt5==5.13.2
    - pyqt5-sip==12.7.0
    - pyrsistent==0.15.6
    - pytest==5.3.1
    - pyyaml==5.2
    - ray==0.7.6
    - redis==3.3.11
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rope==0.16.0
    - rsa==4.6
    - scipy==1.3.3
    - setproctitle==1.1.10
    - shutilwhich==1.1.0
    - tempdir==0.7.1
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.2.0rc3
    - tensorflow-estimator==2.2.0rc0
    - termcolor==1.1.0
    - tqdm==4.40.2
    - urllib3==1.25.7
    - wcwidth==0.1.7
    - werkzeug==1.0.1
    - zipp==0.6.0
prefix: /home/james/anaconda3/envs/gridworld

